# -*- mode: ruby -*-
# vi: set ft=ruby :


# PHP-CSAS Vagrant Configuration
Vagrant.configure(2) do |config|
  # For vagrant config reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Use Ubuntu Server 14.04 LTS (Trusty Tahr)
  config.vm.box = "ubuntu/trusty64"

  # Disable automatic box update checking.
  config.vm.box_check_update = false

  # Forward ports for Apache Web Server
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443


  # Virtualbox Specific configs
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2056"
  end

  # Setup the development environment on the machine
  config.vm.provision "shell", privileged: false, path: "bootstrap.sh"
end
